name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          username: ${{ secrets.USERNAME }}
          api-key: ${{ secrets.API_KEY }}
          url: ${{ secrets.URL }}
          stream: ${{ secrets.STREAM }}
          topic: ${{ secrets.TOPIC }}
          message: |-
            Message from test workflow using mutli-line YAML string to ensure we can send fully formatted Zulip messages

            Text formatting: *italic* **bold** ~~strikethrough~~

            Links: [Zulip website](https://zulip.org)

            Emojis (from [Noto Emoji](https://www.google.com/get/noto/help/emoji)): :heart: :monkey: :grapes:

            Spoilers:
            ```spoiler Always visible heading
            This text won't be visible until the user clicks.
            ```

            Unordered, ordered, and nested lists:
            * Milk
            * Tea
              1. Green tea
              1. Black tea
              1. Oolong tea
            * Coffee

            Code blocks with syntax highlighting:
            ```json
            {
              "foo": "bar"
            }
            ```

            Tables:

            | Tables        | Are           | Cool  |
            | ------------- |:-------------:| -----:|
            | col 3 is      | right-aligned | $1600 |
            | col 2 is      | centered      |   $12 |
            | zebra stripes | are neat      |    $1 |
